/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Maslenitsa (https://sketchfab.com/macro.zlo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/the-wizards-enigmatic-cabin-14c524e52749403eab0245394621b3d8
title: The Wizard's Enigmatic Cabin
*/

import { useGLTF } from '@react-three/drei'
import { MeshProps } from '@react-three/fiber'
import { useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    things_01_MH_part1_0: THREE.Mesh
    things_02_MH_part1_0: THREE.Mesh
    things_03_MH_part1_0: THREE.Mesh
    things_04_MH_part1_0: THREE.Mesh
    things_05_MH_part1_0: THREE.Mesh
    things_06_MH_part1_0: THREE.Mesh
    things_07_MH_part1_0: THREE.Mesh
    things_08_MH_part1_0: THREE.Mesh
    things_09_MH_part1_0: THREE.Mesh
    things_10_MH_part1_0: THREE.Mesh
    things_11_MH_part1_0: THREE.Mesh
    things_12_MH_part1_0: THREE.Mesh
    things_13_MH_part1_0: THREE.Mesh
    roof_1_low_MH_part1_0: THREE.Mesh
    things_15_MH_part1_0: THREE.Mesh
    things_16_MH_part1_0: THREE.Mesh
    field_low_MH_part2_0: THREE.Mesh
    flover_01_low_MH_part2_0: THREE.Mesh
    flover_02_low_MH_part2_0: THREE.Mesh
    flover_03_low_MH_part2_0: THREE.Mesh
    flover_04_low_MH_part2_0: THREE.Mesh
    flover_05_low_MH_part2_0: THREE.Mesh
    flover_06_low_MH_part2_0: THREE.Mesh
    flover_07_low_MH_part2_0: THREE.Mesh
    flover_08_low_MH_part2_0: THREE.Mesh
    flover_09_low_MH_part2_0: THREE.Mesh
    flover_10_low_MH_part2_0: THREE.Mesh
    flover_11_low_MH_part2_0: THREE.Mesh
    flover_12_low_MH_part2_0: THREE.Mesh
    flover_13_low_MH_part2_0: THREE.Mesh
    flover_14_low_MH_part2_0: THREE.Mesh
    flover_15_low_MH_part2_0: THREE.Mesh
    flover_16_low_MH_part2_0: THREE.Mesh
    stone_big_23_low_MH_part3_0: THREE.Mesh
    stone_big_22_low_MH_part3_0: THREE.Mesh
    stone_big_19_low_MH_part3_0: THREE.Mesh
    stone_big_30_low_MH_part3_0: THREE.Mesh
    stone_big_31_low_MH_part3_0: THREE.Mesh
    stone_big_17_low_MH_part3_0: THREE.Mesh
    stone_big_27_low_MH_part3_0: THREE.Mesh
    stone_big_28_low_MH_part3_0: THREE.Mesh
    stone_big_32_low_MH_part3_0: THREE.Mesh
    stone_big_14_low_MH_part3_0: THREE.Mesh
    stone_big_09_low_MH_part3_0: THREE.Mesh
    stone_big_18_low_MH_part3_0: THREE.Mesh
    stone_big_42_low_MH_part3_0: THREE.Mesh
    stone_big_24_low_MH_part3_0: THREE.Mesh
    stone_big_11_low_MH_part3_0: THREE.Mesh
    stone_big_25_low_MH_part3_0: THREE.Mesh
    stone_big_40_low_MH_part3_0: THREE.Mesh
    stone_big_20_low_MH_part3_0: THREE.Mesh
    stone_big_36_low_MH_part3_0: THREE.Mesh
    stone_big_26_low_MH_part3_0: THREE.Mesh
    stone_big_33_low_MH_part3_0: THREE.Mesh
    stone_big_06_low_MH_part3_0: THREE.Mesh
    stone_big_10_low_MH_part3_0: THREE.Mesh
    stone_big_43_low_MH_part3_0: THREE.Mesh
    stone_big_46_low_MH_part3_0: THREE.Mesh
    stone_big_05_low_MH_part3_0: THREE.Mesh
    stone_big_07_low_MH_part3_0: THREE.Mesh
    stone_big_03_low_MH_part3_0: THREE.Mesh
    stone_big_04_low_MH_part3_0: THREE.Mesh
    stone_big_02_low_MH_part3_0: THREE.Mesh
    stone_big_01_low_MH_part3_0: THREE.Mesh
    stone_big_39_low_MH_part3_0: THREE.Mesh
    stone_big_41_low_MH_part3_0: THREE.Mesh
    stone_big_38_low_MH_part3_0: THREE.Mesh
    stone_big_12_low_MH_part3_0: THREE.Mesh
    stone_big_45_low_MH_part3_0: THREE.Mesh
    stone_big_35_low_MH_part3_0: THREE.Mesh
    stone_big_29_low_MH_part3_0: THREE.Mesh
    stone_big_44_low_MH_part3_0: THREE.Mesh
    stone_big_37_low_MH_part3_0: THREE.Mesh
    stone_big_15_low_MH_part3_0: THREE.Mesh
    stone_big_13_low_MH_part3_0: THREE.Mesh
    stone_big_21_low_MH_part3_0: THREE.Mesh
    stone_big_08_low_MH_part3_0: THREE.Mesh
    stone_big_16_low_MH_part3_0: THREE.Mesh
    wood_beam_30_low_low_MH_part4_0: THREE.Mesh
    wood_beam_14_low_low_MH_part4_0: THREE.Mesh
    wood_beam_31_low_low_MH_part4_0: THREE.Mesh
    wood_beam_45_low_low_MH_part4_0: THREE.Mesh
    wood_beam_02_low_low_MH_part4_0: THREE.Mesh
    wood_beam_39_low_low_MH_part4_0: THREE.Mesh
    wood_beam_18_low_low_MH_part4_0: THREE.Mesh
    wood_beam_22_low_low_MH_part4_0: THREE.Mesh
    wood_beam_43_low_low_MH_part4_0: THREE.Mesh
    wood_beam_53_low_low_MH_part4_0: THREE.Mesh
    wood_beam_29_low_low_MH_part4_0: THREE.Mesh
    wood_beam_36_low_low_MH_part4_0: THREE.Mesh
    wood_beam_46_low_low_MH_part4_0: THREE.Mesh
    wood_beam_13_low_low_MH_part4_0: THREE.Mesh
    wood_beam_42_low_low_MH_part4_0: THREE.Mesh
    wood_beam_16_low_low_MH_part4_0: THREE.Mesh
    wood_beam_44_low_low_MH_part4_0: THREE.Mesh
    wood_beam_03_low_low_MH_part4_0: THREE.Mesh
    wood_beam_41_low_low_MH_part4_0: THREE.Mesh
    wood_beam_55_low_low_MH_part4_0: THREE.Mesh
    wood_beam_56_low_low_MH_part4_0: THREE.Mesh
    wood_beam_08_low_low_MH_part4_0: THREE.Mesh
    wood_beam_57_low_low_MH_part4_0: THREE.Mesh
    wood_beam_10_low_low_MH_part4_0: THREE.Mesh
    wood_beam_23_low_low_MH_part4_0: THREE.Mesh
    wood_beam_24_low_low_MH_part4_0: THREE.Mesh
    wood_beam_01_low_low_MH_part4_0: THREE.Mesh
    wood_beam_32_low_low_MH_part4_0: THREE.Mesh
    wood_beam_17_low_low_MH_part4_0: THREE.Mesh
    wood_beam_12_low_low_MH_part4_0: THREE.Mesh
    wood_beam_62_low_low_MH_part4_0: THREE.Mesh
    wood_beam_06_low_low_MH_part4_0: THREE.Mesh
    wood_beam_28_low_low_MH_part4_0: THREE.Mesh
    wood_beam_09_low_low_MH_part4_0: THREE.Mesh
    wood_beam_38_low_low_MH_part4_0: THREE.Mesh
    wood_beam_40_low_low_MH_part4_0: THREE.Mesh
    wood_beam_19_low_low_MH_part4_0: THREE.Mesh
    wood_beam_21_low_low_MH_part4_0: THREE.Mesh
    wood_beam_20_low_low_MH_part4_0: THREE.Mesh
    wood_beam_59_low_low_MH_part4_0: THREE.Mesh
    wood_beam_07_low_low_MH_part4_0: THREE.Mesh
    wood_beam_49_low_low_MH_part4_0: THREE.Mesh
    wood_beam_58_low_low_MH_part4_0: THREE.Mesh
    wood_beam_27_low_low_MH_part4_0: THREE.Mesh
    wood_beam_34_low_low_MH_part4_0: THREE.Mesh
    wood_beam_11_low_low_MH_part4_0: THREE.Mesh
    wood_beam_15_low_low_MH_part4_0: THREE.Mesh
    wood_beam_37_low_low_MH_part4_0: THREE.Mesh
    wood_beam_35_low_low_MH_part4_0: THREE.Mesh
    wood_beam_47_low_low_MH_part4_0: THREE.Mesh
    wood_beam_61_low_low_MH_part4_0: THREE.Mesh
    wood_beam_05_low_low_MH_part4_0: THREE.Mesh
    wood_beam_54_low_low_MH_part4_0: THREE.Mesh
    wood_beam_51_low_low_MH_part4_0: THREE.Mesh
    wood_beam_60_low_low_MH_part4_0: THREE.Mesh
    wood_beam_52_low_low_MH_part4_0: THREE.Mesh
    wood_beam_50_low_low_MH_part4_0: THREE.Mesh
    wood_beam_04_low_low_MH_part4_0: THREE.Mesh
    wood_beam_25_low_low_MH_part4_0: THREE.Mesh
    wood_beam_26_low_low_MH_part4_0: THREE.Mesh
    wood_beam_48_low_low_MH_part4_0: THREE.Mesh
    wood_beam_33_low_low_MH_part4_0: THREE.Mesh
    wood_house_22_low_MH_part4_0: THREE.Mesh
    wood_house_23_low_MH_part4_0: THREE.Mesh
    wood_house_24_low_MH_part4_0: THREE.Mesh
    wood_house_19_low_MH_part4_0: THREE.Mesh
    wood_house_20_low_MH_part4_0: THREE.Mesh
    wood_house_21_low_MH_part4_0: THREE.Mesh
    wood_house_10_low_MH_part4_0: THREE.Mesh
    wood_house_11_low_MH_part4_0: THREE.Mesh
    wood_house_12_low_MH_part4_0: THREE.Mesh
    wood_house_09_low_MH_part4_0: THREE.Mesh
    wood_house_15_low_MH_part4_0: THREE.Mesh
    wood_house_16_low_MH_part4_0: THREE.Mesh
    wood_house_14_low_MH_part4_0: THREE.Mesh
    wood_house_13_low_MH_part4_0: THREE.Mesh
    wood_house_07_low_MH_part4_0: THREE.Mesh
    wood_house_35_low_MH_part4_0: THREE.Mesh
    wood_house_34_low_MH_part4_0: THREE.Mesh
    wood_house_28_low_MH_part4_0: THREE.Mesh
    wood_house_01_low_MH_part4_0: THREE.Mesh
    wood_house_32_low_MH_part4_0: THREE.Mesh
    wood_house_02_low_MH_part4_0: THREE.Mesh
    wood_house_43_low_MH_part4_0: THREE.Mesh
    wood_house_42_low_MH_part4_0: THREE.Mesh
    wood_house_44_low_MH_part4_0: THREE.Mesh
    wood_house_45_low_MH_part4_0: THREE.Mesh
    wood_house_36_low_MH_part4_0: THREE.Mesh
    wood_house_37_low_MH_part4_0: THREE.Mesh
    wood_house_38_low_MH_part4_0: THREE.Mesh
    wood_house_39_low_MH_part4_0: THREE.Mesh
    wood_house_40_low_MH_part4_0: THREE.Mesh
    wood_house_41_low_MH_part4_0: THREE.Mesh
    wood_house_08_low_MH_part4_0: THREE.Mesh
    wood_house_06_low_MH_part4_0: THREE.Mesh
    wood_house_05_low_MH_part4_0: THREE.Mesh
    wood_house_04_low_MH_part4_0: THREE.Mesh
    wood_house_26_low_MH_part4_0: THREE.Mesh
    wood_house_27_low_MH_part4_0: THREE.Mesh
    wood_house_25_low_MH_part4_0: THREE.Mesh
    wood_house_17_low_MH_part4_0: THREE.Mesh
    wood_house_18_low_MH_part4_0: THREE.Mesh
    wood_house_03_low_MH_part4_0: THREE.Mesh
    wood_house_29_low_MH_part4_0: THREE.Mesh
    wood_house_30_low_MH_part4_0: THREE.Mesh
    wood_house_33_low_MH_part4_0: THREE.Mesh
    wood_house_31_low_MH_part4_0: THREE.Mesh
    flover_14_low001_MH_part2_0: THREE.Mesh
    flover_14_low002_MH_part2_0: THREE.Mesh
    flover_15_low001_MH_part2_0: THREE.Mesh
    flover_15_low002_MH_part2_0: THREE.Mesh
    things_017_MH_part1_0: THREE.Mesh
    things_018_MH_part1_0: THREE.Mesh
    things_019_MH_part1_0: THREE.Mesh
    things_020_MH_part1_0: THREE.Mesh
    things_021_MH_part1_0: THREE.Mesh
    Object092_MH_part1_0: THREE.Mesh
    things_022_MH_part1_0: THREE.Mesh
    Object093_MH_part1_0: THREE.Mesh
    things_023_MH_part1_0: THREE.Mesh
    things_024_MH_part1_0: THREE.Mesh
    things_025_MH_part1_0: THREE.Mesh
    things_026_MH_part1_0: THREE.Mesh
    things_027_MH_part1_0: THREE.Mesh
    things_028_MH_part1_0: THREE.Mesh
    things_029_MH_part1_0: THREE.Mesh
    Object094_MH_part1_0: THREE.Mesh
    things_030_MH_part1_0: THREE.Mesh
    things_031_MH_part1_0: THREE.Mesh
    things_032_MH_part1_0: THREE.Mesh
    Object095_MH_part1_0: THREE.Mesh
    things_033_MH_part1_0: THREE.Mesh
    things_034_MH_part1_0: THREE.Mesh
    things_035_MH_part1_0: THREE.Mesh
    things_036_MH_part1_0: THREE.Mesh
    things_037_MH_part1_0: THREE.Mesh
    Line121_MH_part1_0: THREE.Mesh
    Line122_MH_part1_0: THREE.Mesh
    Line123_MH_part1_0: THREE.Mesh
    Line124_MH_part1_0: THREE.Mesh
    Line125_MH_part1_0: THREE.Mesh
    Line126_MH_part1_0: THREE.Mesh
    Line127_MH_part1_0: THREE.Mesh
    things_038_MH_part1_0: THREE.Mesh
    Line128_MH_part1_0: THREE.Mesh
    Object208_MH_part1_0: THREE.Mesh
    things_011_MH_part1_0: THREE.Mesh
    Object209_MH_part1_0: THREE.Mesh
    Object211_MH_part1_0: THREE.Mesh
    Object212_MH_part1_0: THREE.Mesh
    Object213_MH_part1_0: THREE.Mesh
    things_012_MH_part1_0: THREE.Mesh
    Object214_MH_part1_0: THREE.Mesh
    Object215_MH_part1_0: THREE.Mesh
    Object216_MH_part1_0: THREE.Mesh
    Object217_MH_part1_0: THREE.Mesh
    Object218_MH_part1_0: THREE.Mesh
    Object219_MH_part1_0: THREE.Mesh
    Object220_MH_part1_0: THREE.Mesh
    Plane001_MH_part1_0: THREE.Mesh
    stone_big_12_low001_MH_part3_0: THREE.Mesh
    Object221_MH_part3_0: THREE.Mesh
    moss_low001_MH_part1_0: THREE.Mesh
    Box001_MH_part1_0: THREE.Mesh
    wood_beam_27_low_low001_MH_part4_0: THREE.Mesh
  }
  materials: {
    MH_part1: THREE.MeshStandardMaterial
    MH_part2: THREE.MeshStandardMaterial
    MH_part3: THREE.MeshStandardMaterial
    MH_part4: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: MeshProps) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-519.53, 0, -405.62]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.things_01_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-481.67, -8.98, -615.83]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.things_02_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-395.51, -16.3, -812.65]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.things_03_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-259.85, -3.15, -975.95]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.things_04_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-498.53, -14.67, -514.18]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-6.05, -29.39, 57.73]}>
              <mesh
                geometry={nodes.things_05_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-538.14, 0, -413.42]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.things_06_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-404.82, 61.6, -398.96]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.things_07_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-404.82, 61.6, -398.96]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.things_08_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[3.12, 669.34, 96.86]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.things_09_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-41.36, -26.6, -1042.52]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.things_10_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-403.66, 10.2, -393.9]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.things_11_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.things_12_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.things_13_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[223.51, 426.22, -377.2]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.roof_1_low_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.things_15_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.things_16_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.field_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[309.43, 1003.16, -304.16]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_01_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[391.85, 103.07, -703.23]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_02_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[405.14, 43.19, -734.71]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_03_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[249.96, 61.41, -829.61]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_04_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[453.34, 30.29, -134.5]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_05_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[488.17, 69.05, -168.67]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_06_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[366.37, 45.68, 2.32]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_07_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[359.36, 151.42, -1.08]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_08_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[230.95, 132.46, -73.14]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_09_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[198.22, 99.67, -188.62]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_10_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[235.93, 32.31, -49.27]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_11_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[218.68, 923.27, -674.24]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.flover_12_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[156.9, 1454.87, 23.88]}
            rotation={[-1.17, 0.18, 0.4]}
          >
            <mesh
              geometry={nodes.flover_13_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[156.9, 1454.87, 23.88]}
            rotation={[-1.17, 0.18, 0.4]}
          >
            <mesh
              geometry={nodes.flover_14_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[156.9, 1454.87, 23.88]}
            rotation={[-1.17, 0.18, 0.4]}
          >
            <mesh
              geometry={nodes.flover_15_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[5.23, 1624.5, -289.87]}
            rotation={[-1.17, 0.18, 0.4]}
          >
            <mesh
              geometry={nodes.flover_16_low_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[-404.3, -342.07, -571.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[772.65, 51.17, -794.62]}>
              <mesh
                geometry={nodes.stone_big_23_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-299.28, -477.32, -362.6]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[667.64, 260, -659.37]}>
              <mesh
                geometry={nodes.stone_big_22_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-120.94, -498.23, -224.3]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[489.3, 398.3, -638.46]}>
              <mesh
                geometry={nodes.stone_big_19_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[13.21, -549.7, -922.58]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[355.15, -299.98, -586.99]}>
              <mesh
                geometry={nodes.stone_big_30_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-57.92, -768.67, -548.65]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[426.28, 73.95, -368.02]}>
              <mesh
                geometry={nodes.stone_big_31_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-326.65, -304.36, -791.77]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[695.01, -169.17, -832.33]}>
              <mesh
                geometry={nodes.stone_big_17_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-179.53, -136.08, -996.12]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[547.89, -373.52, -1000.61]}>
              <mesh
                geometry={nodes.stone_big_27_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-110, -134.01, -1087.65]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[478.35, -465.05, -1002.68]}>
              <mesh
                geometry={nodes.stone_big_28_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[43.29, -41.81, -1188.27]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[325.06, -565.67, -1094.88]}>
              <mesh
                geometry={nodes.stone_big_32_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[90.32, 57.02, -1133.22]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[278.03, -510.62, -1193.72]}>
              <mesh
                geometry={nodes.stone_big_14_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[188.33, -167.89, -1198.58]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[180.02, -575.98, -968.8]}>
              <mesh
                geometry={nodes.stone_big_09_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[340.8, -925.05, -624.42]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[27.55, -1.82, -211.64]}>
              <mesh
                geometry={nodes.stone_big_18_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[558.33, -243.99, -1038.33]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-189.98, -415.73, -892.7]}>
              <mesh
                geometry={nodes.stone_big_42_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[617.98, -632.47, 12.74]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-249.63, 635.34, -504.22]}>
              <mesh
                geometry={nodes.stone_big_24_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[531.24, -556.46, 208.81]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-162.89, 831.41, -580.23]}>
              <mesh
                geometry={nodes.stone_big_11_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[412.06, -370.59, 382.8]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-43.71, 1005.4, -766.1]}>
              <mesh
                geometry={nodes.stone_big_25_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[256.72, -263.5, 470.38]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[111.63, 1092.98, -873.19]}>
              <mesh
                geometry={nodes.stone_big_40_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[766.34, -639.5, -191.92]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-397.99, 430.68, -497.19]}>
              <mesh
                geometry={nodes.stone_big_20_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[849.12, -634.13, -488.73]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-480.76, 133.87, -502.56]}>
              <mesh
                geometry={nodes.stone_big_36_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[881.86, -520.29, -311.65]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-513.5, 310.95, -616.4]}>
              <mesh
                geometry={nodes.stone_big_26_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[695.22, -405.59, -832.11]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-326.86, -209.51, -731.1]}>
              <mesh
                geometry={nodes.stone_big_33_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[739.34, -496.95, -577.65]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-370.99, 44.95, -639.74]}>
              <mesh
                geometry={nodes.stone_big_06_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[454.08, 107.44, -1128.96]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-85.73, -506.36, -1244.13]}>
              <mesh
                geometry={nodes.stone_big_10_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[779.92, -600.4, 5.92]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-411.57, 628.52, -536.29]}>
              <mesh
                geometry={nodes.stone_big_43_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[788.27, -307.65, -344.42]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-419.91, 278.18, -829.04]}>
              <mesh
                geometry={nodes.stone_big_46_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[1049.07, -231.62, -413.94]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-680.71, 208.66, -905.07]}>
              <mesh
                geometry={nodes.stone_big_05_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[903.59, -229.62, 19.91]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-535.24, 642.51, -907.08]}>
              <mesh
                geometry={nodes.stone_big_07_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[1003.26, -133.98, -117.17]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-634.91, 505.43, -1002.71]}>
              <mesh
                geometry={nodes.stone_big_03_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[1047.35, -123.18, -255.38]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-678.99, 367.22, -1013.51]}>
              <mesh
                geometry={nodes.stone_big_04_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[673.57, -243.56, 147.78]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-305.21, 770.38, -893.13]}>
              <mesh
                geometry={nodes.stone_big_02_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[501.3, -329.81, 178]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-132.95, 800.6, -806.88]}>
              <mesh
                geometry={nodes.stone_big_01_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[323.73, -86.57, 212.14]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[44.63, 834.74, -1050.12]}>
              <mesh
                geometry={nodes.stone_big_39_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[163.55, -89.57, 177.45]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[204.81, 800.05, -1047.12]}>
              <mesh
                geometry={nodes.stone_big_41_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[453.99, -212.52, 258.68]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-85.64, 881.28, -924.17]}>
              <mesh
                geometry={nodes.stone_big_38_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[277.92, -602.23, 193.84]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[90.43, 816.44, -534.46]}>
              <mesh
                geometry={nodes.stone_big_12_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-12.41, -40.91, 186.46]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[380.76, 809.06, -1095.78]}>
              <mesh
                geometry={nodes.stone_big_45_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[790.14, -157.84, -312.47]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-421.78, 310.13, -978.85]}>
              <mesh
                geometry={nodes.stone_big_35_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[723.89, -310.2, -64.39]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-355.53, 558.21, -826.49]}>
              <mesh
                geometry={nodes.stone_big_29_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[757.63, -158.89, -237.14]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-389.27, 385.46, -977.8]}>
              <mesh
                geometry={nodes.stone_big_44_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[639.08, 65.77, -1195.51]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-270.72, -572.91, -1202.46]}>
              <mesh
                geometry={nodes.stone_big_37_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-235.27, -365.19, 86.31]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[603.62, 708.91, -771.5]}>
              <mesh
                geometry={nodes.stone_big_15_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-283.31, -219.71, 304.23]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[651.67, 926.83, -916.98]}>
              <mesh
                geometry={nodes.stone_big_13_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-119.07, -335.36, 235.74]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[487.42, 858.34, -801.34]}>
              <mesh
                geometry={nodes.stone_big_21_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[182.92, -466.52, 96.15]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[185.44, 718.75, -670.18]}>
              <mesh
                geometry={nodes.stone_big_08_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[444.14, -144.69, -1203.9]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-75.78, -581.3, -992]}>
              <mesh
                geometry={nodes.stone_big_16_low_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[364.2, 454.81, -232.56]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_30_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[474.4, 454.39, -231.16]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_14_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[419.57, 368.7, -218.26]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_31_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[600.44, 194.22, -241.6]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_45_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[600.46, 194.23, -618.27]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_02_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[177.1, 194.47, -627.52]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_39_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[177.25, 194.81, -229.95]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_18_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[627.66, 610.16, -428.57]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_22_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[611.72, 313.6, -430.76]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_43_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[408.5, 314.94, -217.28]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_53_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[408.5, 314.94, -642.16]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_29_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[377.25, 76.69, -594.83]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_36_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[377.55, 76.98, -265.02]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_46_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[607.21, 382.33, -492.87]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_13_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[607.49, 382.14, -364.96]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_42_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[617.67, 446.5, -428.85]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_16_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[606.49, 76.29, -429.98]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_44_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[609.1, 422.5, -569.38]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_03_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[608.79, 422.76, -287.28]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_41_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[12.27, 472.61, -17.21]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_55_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-43.99, 412.54, -17.72]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_56_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[68.34, 412.32, -17.78]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_08_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[12.3, 369.23, -15.86]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_57_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-158.65, 477.05, -333.96]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_10_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-157.26, 477.47, -444.74]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_23_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-171.56, 391.35, -389.36]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_24_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[490.89, 196.29, -232.37]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_01_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[348.73, 196.28, -234.34]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_32_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[418.9, 140.99, -248.46]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_17_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[417.93, 248.69, -216.15]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_12_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-126.26, 194.21, -22.6]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_62_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[154.6, 194.23, -22.44]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_06_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-134.75, 196.3, -476.23]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_28_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-126.49, 194.21, -754.66]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_09_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[154.59, 194.22, -754.86]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_38_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[161.66, 195.8, -640.97]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_40_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[164.1, 195.8, -217.69]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_19_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[13.32, 627.07, -769.74]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_21_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[12.74, 729.65, 9.66]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_20_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[123.24, 493.82, -15.23]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_59_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[75.91, 152.15, -7.28]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_07_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-51.66, 152.31, -7.32]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_49_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-97.71, 493.79, -15.14]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_58_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-136.58, 195.91, -299.47]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_27_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-50.63, 382.02, -760.12]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_34_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[76.6, 381.7, -760.17]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_11_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[13.25, 454, -771.76]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_15_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[13.06, 76.1, -763.89]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_37_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[9.92, 313.61, -762.96]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_35_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[127.58, 76.68, -388.94]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_47_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-151.36, 326.27, -381.95]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_61_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[178.25, 326.82, -95.64]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_05_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[178.23, 326.82, -714]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_54_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[94.65, 76.41, -15.83]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_51_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[7.92, 315.37, -12.81]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_60_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-67.61, 76.62, -16.08]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_52_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-102.11, 76.7, -389.26]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_50_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[132.58, 442.88, -767.44]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_04_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-151.28, 249.25, -388.01]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_25_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-120.32, 140.5, -387.92]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_26_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[12.17, 256.42, -2.46]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_48_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[-106.83, 441.09, -767.85]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_33_low_low_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
          <group
            position={[385, 440.92, -232.89]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-385, -232.89, -440.92]}>
              <mesh
                geometry={nodes.wood_house_22_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[454.42, 440.94, -232.89]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-454.42, -232.89, -440.94]}>
              <mesh
                geometry={nodes.wood_house_23_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[419.36, 385.78, -232.9]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-419.36, -232.9, -385.78]}>
              <mesh
                geometry={nodes.wood_house_24_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-155.55, 463.83, -424.21]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[155.55, -424.21, -463.83]}>
              <mesh
                geometry={nodes.wood_house_19_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-155.55, 463.85, -354.58]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[155.55, -354.58, -463.85]}>
              <mesh
                geometry={nodes.wood_house_20_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-155.55, 408.46, -389.7]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[155.55, -389.7, -408.46]}>
              <mesh
                geometry={nodes.wood_house_21_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-127.71, 197.74, -459.21]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[127.71, -459.21, -197.74]}>
              <mesh
                geometry={nodes.wood_house_10_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-127.82, 197.68, -317.41]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[127.82, -317.41, -197.68]}>
              <mesh
                geometry={nodes.wood_house_11_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-136.86, 237.07, -388.33]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[136.86, -388.33, -237.07]}>
              <mesh
                geometry={nodes.wood_house_12_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-118.72, 158.6, -388.34]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[118.72, -388.34, -158.6]}>
              <mesh
                geometry={nodes.wood_house_09_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[367.57, 197.67, -240.67]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-367.57, -240.67, -197.67]}>
              <mesh
                geometry={nodes.wood_house_15_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[473.51, 197.67, -240.67]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-473.51, -240.67, -197.67]}>
              <mesh
                geometry={nodes.wood_house_16_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[420.55, 158.54, -249.74]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-420.55, -249.74, -158.54]}>
              <mesh
                geometry={nodes.wood_house_14_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[420.55, 237.03, -231.54]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-420.55, -231.54, -237.03]}>
              <mesh
                geometry={nodes.wood_house_13_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-154.47, 452.97, -389.3]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[154.47, -389.3, -452.97]}>
              <mesh
                geometry={nodes.wood_house_07_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-127.63, 197.82, -388.31]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[127.63, -388.31, -197.82]}>
              <mesh
                geometry={nodes.wood_house_35_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-127.16, 197.82, -388.46]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[127.16, -388.46, -197.82]}>
              <mesh
                geometry={nodes.wood_house_34_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-105.11, 545.65, -376.39]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[105.11, -376.39, -545.65]}>
              <mesh
                geometry={nodes.wood_house_28_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[130.73, 544.22, -376.35]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-130.73, -376.35, -544.22]}>
              <mesh
                geometry={nodes.wood_house_01_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-166.26, 471.6, -324.97]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[166.26, -324.97, -471.6]}>
              <mesh
                geometry={nodes.wood_house_32_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-165.86, 472.43, -452.86]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[165.86, -452.86, -472.43]}>
              <mesh
                geometry={nodes.wood_house_02_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[58.25, 157.98, -18.87]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-58.25, -18.87, -157.98]}>
              <mesh
                geometry={nodes.wood_house_43_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-32.8, 157.98, -18.86]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[32.8, -18.86, -157.98]}>
              <mesh
                geometry={nodes.wood_house_42_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[12.91, 73.8, -18.93]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-12.91, -18.93, -73.8]}>
              <mesh
                geometry={nodes.wood_house_44_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[12.93, 235.62, -18.93]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-12.93, -18.93, -235.62]}>
              <mesh
                geometry={nodes.wood_house_45_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[12.55, 195.03, -19.01]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-12.99, -18.25, -195.03]}>
              <mesh
                geometry={nodes.wood_house_36_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[12.6, 195.38, -19.68]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-12.99, -19, -195.03]}>
              <mesh
                geometry={nodes.wood_house_37_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-14.77, 195.55, -18.45]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[14.77, -18.45, -195.55]}>
              <mesh
                geometry={nodes.wood_house_38_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[40.59, 195.55, -18.45]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-40.59, -18.45, -195.55]}>
              <mesh
                geometry={nodes.wood_house_39_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[12.88, 174.5, -18.45]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-12.88, -18.45, -174.5]}>
              <mesh
                geometry={nodes.wood_house_40_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[12.88, 216.34, -18.45]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-12.88, -18.45, -216.34]}>
              <mesh
                geometry={nodes.wood_house_41_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[12.76, 127.6, -19.08]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-12.76, -19.08, -127.6]}>
              <mesh
                geometry={nodes.wood_house_08_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[420.55, 197.82, -240.6]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-420.55, -240.6, -197.82]}>
              <mesh
                geometry={nodes.wood_house_06_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[419.79, 430.92, -234.13]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-419.79, -234.13, -430.92]}>
              <mesh
                geometry={nodes.wood_house_05_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[12.27, 414.79, -21.69]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-12.27, -21.69, -414.79]}>
              <mesh
                geometry={nodes.wood_house_04_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[12.27, 456.61, -21.69]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-12.27, -21.69, -456.61]}>
              <mesh
                geometry={nodes.wood_house_26_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[51.48, 429.14, -21.69]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-51.48, -21.69, -429.14]}>
              <mesh
                geometry={nodes.wood_house_27_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-27.14, 429.2, -21.69]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[27.14, -21.69, -429.2]}>
              <mesh
                geometry={nodes.wood_house_25_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[-33.09, 413.44, -22.66]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[33.09, -22.66, -413.44]}>
              <mesh
                geometry={nodes.wood_house_17_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[60.49, 413.41, -22.31]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-60.49, -22.31, -413.41]}>
              <mesh
                geometry={nodes.wood_house_18_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[13.89, 462.24, -21.67]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-13.89, -21.67, -462.24]}>
              <mesh
                geometry={nodes.wood_house_03_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[460.27, 475.27, -284.64]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-460.27, -284.64, -475.27]}>
              <mesh
                geometry={nodes.wood_house_29_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[446.88, 474.69, -573.2]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-446.88, -573.2, -474.69]}>
              <mesh
                geometry={nodes.wood_house_30_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[420.34, 458.87, -215.07]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-420.34, -215.07, -458.87]}>
              <mesh
                geometry={nodes.wood_house_33_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[420.34, 458.87, -215.07]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-420.34, -215.07, -458.87]}>
              <mesh
                geometry={nodes.wood_house_31_low_MH_part4_0.geometry}
                material={materials.MH_part4}
              />
            </group>
          </group>
          <group
            position={[156.9, 1454.87, 23.88]}
            rotation={[-1.17, 0.18, 0.4]}
          >
            <mesh
              geometry={nodes.flover_14_low001_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[156.9, 1454.87, 23.88]}
            rotation={[-1.17, 0.18, 0.4]}
          >
            <mesh
              geometry={nodes.flover_14_low002_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[156.9, 1454.87, 23.88]}
            rotation={[-1.17, 0.18, 0.4]}
          >
            <mesh
              geometry={nodes.flover_15_low001_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[156.9, 1454.87, 23.88]}
            rotation={[-1.17, 0.18, 0.4]}
          >
            <mesh
              geometry={nodes.flover_15_low002_MH_part2_0.geometry}
              material={materials.MH_part2}
            />
          </group>
          <group
            position={[-434, -2.85, 9.29]}
            rotation={[-Math.PI / 2, 0, -2.18]}
          >
            <mesh
              geometry={nodes.things_017_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-317.71, -3.15, 177.64]}
            rotation={[-Math.PI / 2, 0, -1.75]}
          >
            <mesh
              geometry={nodes.things_018_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-501.4, -0.33, -193.42]}
            rotation={[-Math.PI / 2, 0, -2.62]}
          >
            <mesh
              geometry={nodes.things_019_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-87.59, -5.72, -1097.51]}
            rotation={[-Math.PI / 2, 0, 2.27]}
          >
            <mesh
              geometry={nodes.things_020_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-326.17, -18.78, -897.7]}
            rotation={[Math.PI / 2, 0, -2.27]}
          >
            <group position={[-6.05, -29.39, -13.32]}>
              <mesh
                geometry={nodes.things_021_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-436.3, -15.17, -716.03]}
            rotation={[1.53, -0.01, -2.83]}
          >
            <group position={[5.38, 194.78, -17.25]}>
              <mesh
                geometry={nodes.Object092_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-179.23, -14.94, -1031.61]}
            rotation={[1.55, -0.05, -2.02]}
          >
            <group position={[-6.05, -29.39, -13.32]}>
              <mesh
                geometry={nodes.things_022_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-510.58, -6.67, -301.96]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[5.38, 194.78, 45.96]}>
              <mesh
                geometry={nodes.Object093_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-378.19, -18.78, 92.81]}
            rotation={[Math.PI / 2, 0, -0.43]}
          >
            <group position={[-6.05, -29.39, -13.32]}>
              <mesh
                geometry={nodes.things_023_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-474.81, -14.94, -93.03]}
            rotation={[1.55, -0.05, -0.15]}
          >
            <group position={[-6.05, -29.39, -13.32]}>
              <mesh
                geometry={nodes.things_024_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[817.35, 10.91, -1026.7]}
            rotation={[-Math.PI / 2, 0, 1.56]}
          >
            <mesh
              geometry={nodes.things_025_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[973.08, -28.5, -828.89]}
            rotation={[-Math.PI / 2, 0, 1.14]}
          >
            <mesh
              geometry={nodes.things_026_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[892.5, -26.31, -929.33]}
            rotation={[-1.44, 0.12, 0.64]}
          >
            <mesh
              geometry={nodes.things_027_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[1033.52, -31.69, -715.42]}
            rotation={[1.53, 0.06, 2.99]}
          >
            <group position={[-6.05, -29.39, -13.32]}>
              <mesh
                geometry={nodes.things_028_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[1069.42, -9.76, -597.58]}
            rotation={[-Math.PI / 2, 0, 0.52]}
          >
            <mesh
              geometry={nodes.things_029_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[1082.13, -6.72, -473.71]}
            rotation={[-1.64, 0, -3.13]}
          >
            <group position={[5.38, 194.78, 45.96]}>
              <mesh
                geometry={nodes.Object094_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[1094.52, 0, -352.54]}
            rotation={[-Math.PI / 2, 0, -3.11]}
          >
            <mesh
              geometry={nodes.things_030_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[1065.55, -14.67, -236.41]}
            rotation={[-Math.PI / 2, 0, 3.07]}
          >
            <group position={[-6.05, -29.39, 57.73]}>
              <mesh
                geometry={nodes.things_031_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[1030.82, -12.79, -113.2]}
            rotation={[-Math.PI / 2, 0, 3.06]}
          >
            <mesh
              geometry={nodes.things_032_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[971.36, -18.11, -24.12]}
            rotation={[1.61, 0.02, 0.52]}
          >
            <group position={[5.38, 194.78, -17.25]}>
              <mesh
                geometry={nodes.Object095_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[888.33, -23.4, 88.32]}
            rotation={[-Math.PI / 2, 0, 2.93]}
          >
            <mesh
              geometry={nodes.things_033_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[780.44, -39.29, 142.43]}
            rotation={[Math.PI / 2, 0, 1.14]}
          >
            <group position={[-6.05, -29.39, -13.32]}>
              <mesh
                geometry={nodes.things_034_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[671, -38.69, 197.98]}
            rotation={[-Math.PI / 2, 0, 2.57]}
          >
            <mesh
              geometry={nodes.things_035_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[562.5, -46.2, 205.97]}
            rotation={[1.59, 0.02, 1.71]}
          >
            <group position={[-6.05, -29.39, -13.32]}>
              <mesh
                geometry={nodes.things_036_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[427.63, -37.07, 211.63]}
            rotation={[-Math.PI / 2, 0, -1.53]}
          >
            <mesh
              geometry={nodes.things_037_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[3.2, 633.87, 96.84]}
            rotation={[0, -Math.PI / 6, 0]}
          >
            <group position={[-24.81, -40.34, -29.44]}>
              <mesh
                geometry={nodes.Line121_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group position={[3.2, 633.87, 96.84]} rotation={[0, Math.PI / 3, 0]}>
            <group position={[-24.81, -40.34, -29.44]}>
              <mesh
                geometry={nodes.Line122_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[3.2, 633.87, 96.84]}
            rotation={[Math.PI, Math.PI / 6, -Math.PI]}
          >
            <group position={[-24.81, -40.34, -29.44]}>
              <mesh
                geometry={nodes.Line123_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[3.2, 633.87, 96.84]}
            rotation={[Math.PI, -Math.PI / 3, Math.PI]}
          >
            <group position={[-24.81, -40.34, -29.44]}>
              <mesh
                geometry={nodes.Line124_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[690.46, 502.2, -449.68]}
            rotation={[Math.PI, -1.05, Math.PI]}
          >
            <group position={[-24.81, -40.34, -29.44]}>
              <mesh
                geometry={nodes.Line125_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group position={[690.46, 502.2, -449.68]} rotation={[0, -0.52, 0]}>
            <group position={[-24.81, -40.34, -29.44]}>
              <mesh
                geometry={nodes.Line126_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group position={[690.46, 502.2, -449.68]} rotation={[0, 1.05, 0]}>
            <group position={[-24.81, -40.34, -29.44]}>
              <mesh
                geometry={nodes.Line127_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[690.53, 537.66, -449.7]}
            rotation={[-Math.PI / 2, 0, -3.13]}
          >
            <mesh
              geometry={nodes.things_038_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[690.46, 502.2, -449.68]}
            rotation={[Math.PI, 0.52, -Math.PI]}
          >
            <group position={[-24.81, -40.34, -29.44]}>
              <mesh
                geometry={nodes.Line128_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[25.36, 11.64, -1024.55]}
            rotation={[-2.03, 0.33, -0.24]}
          >
            <group position={[-39.63, 41.23, -1.34]}>
              <mesh
                geometry={nodes.Object208_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-108.75, 491.42, -313.36]}
            rotation={[-1.82, -0.08, -2.63]}
            scale={0.47}
          >
            <group position={[-7.76, -14.03, -1.33]}>
              <mesh
                geometry={nodes.things_011_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-88.04, 500, -326.22]}
            rotation={[-0.78, -0.84, 1.68]}
            scale={0.47}
          >
            <group position={[-39.63, 41.23, -1.34]}>
              <mesh
                geometry={nodes.Object209_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[628.31, -24.7, -677.95]}
            rotation={[-1.66, -0.07, 2.7]}
          >
            <group position={[36.57, -0.16, -1.89]}>
              <mesh
                geometry={nodes.Object211_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[650.85, -33.62, -721.3]}
            rotation={[-1.8, 0.09, 2.74]}
          >
            <group position={[36.3, 53.49, -7.9]}>
              <mesh
                geometry={nodes.Object212_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[581.57, -26.78, -742.48]}
            rotation={[-1.62, 0.06, 2.71]}
            scale={0.91}
          >
            <group position={[-39.63, 41.23, -1.34]}>
              <mesh
                geometry={nodes.Object213_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[582.29, -25.27, -684.22]}
            rotation={[-1.63, 0.06, 2.69]}
          >
            <group position={[-7.76, -14.03, -1.33]}>
              <mesh
                geometry={nodes.things_012_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[749.38, -28.75, -650.94]}
            rotation={[-1.13, 0.36, -1.48]}
          >
            <group position={[36.57, -0.16, -1.89]}>
              <mesh
                geometry={nodes.Object214_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[769.57, -10.44, -610.43]}
            rotation={[-2.79, -0.61, 0.03]}
          >
            <group position={[-39.63, 41.23, -1.34]}>
              <mesh
                geometry={nodes.Object215_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[609.92, -28.02, -238.07]}
            rotation={[-2.7, 0.86, -0.56]}
          >
            <group position={[-39.06, 3.41, 6.2]}>
              <mesh
                geometry={nodes.Object216_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[635.34, -64.34, -234.53]}
            rotation={[-0.89, 0.31, -2.52]}
          >
            <group position={[10.72, -43.24, -14.6]}>
              <mesh
                geometry={nodes.Object217_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-154.36, -3.6, 15.14]}
            rotation={[-1.12, -1.02, 2.93]}
          >
            <group position={[-6.23, -10.23, -46.21]}>
              <mesh
                geometry={nodes.Object218_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-146.22, -3.11, -38.37]}
            rotation={[-1.7, 0.06, -0.75]}
          >
            <group position={[36.57, -0.16, -1.89]}>
              <mesh
                geometry={nodes.Object219_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[-136.66, 16.13, -39.53]}
            rotation={[-0.41, 0.18, 3.08]}
          >
            <group position={[-39.63, 41.23, -1.34]}>
              <mesh
                geometry={nodes.Object220_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[581.01, -512.69, -273.65]}
            rotation={[-2.11, 0.75, 0.78]}
          >
            <mesh
              geometry={nodes.Plane001_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[663.19, -505.06, -202.8]}
            rotation={[2.3, -0.23, -0.67]}
          >
            <group position={[90.43, 816.44, -534.46]}>
              <mesh
                geometry={nodes.stone_big_12_low001_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[684.42, -569.74, -120.65]}
            rotation={[0.72, 0.09, 0.77]}
          >
            <group position={[90.43, 816.44, -534.46]}>
              <mesh
                geometry={nodes.Object221_MH_part3_0.geometry}
                material={materials.MH_part3}
              />
            </group>
          </group>
          <group
            position={[-114.48, 523.43, -323.3]}
            rotation={[-0.84, -0.6, -1.76]}
          >
            <mesh
              geometry={nodes.moss_low001_MH_part1_0.geometry}
              material={materials.MH_part1}
            />
          </group>
          <group
            position={[-404.69, 97.12, -398.89]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.66}
          >
            <group position={[0, 0, -53.86]}>
              <mesh
                geometry={nodes.Box001_MH_part1_0.geometry}
                material={materials.MH_part1}
              />
            </group>
          </group>
          <group
            position={[397.15, 397.16, -608.51]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.wood_beam_27_low_low001_MH_part4_0.geometry}
              material={materials.MH_part4}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
